### ISSUE TITLE
Refactoring to typescript

### ISSUE THREAD

**Issue by galkin** [tcdl/msb#124]
# Clean up tasks

- [x] typescript 2.1 ?
- [x] .npmignore
- [x] autopublish package
- [x] set-up coverrals for typescript
- [x] change naming for env variable
- [x] add SSL for amqp adapter
- [x] Tslint

# Lib

- [x] adapters/amqp/index
- [x] adapters/amqp/publisher
- [x] adapters/amqp/subscriber
- [x] adapters/local
- [x] support/generateId
- [x] support/helpers
- [x] support/logger
- [x] support/serviceDetails
- [x] channelManager
- [x] collector
- [x] config
- [x] messageFactory
- [x] request
- [x] requester
- [x] responder
- [x] responderResponse
- [x] responderServer
- [x] validateWithSchema

# Tests

- [x] support/amqpPublisher
- [x] examples/responder
- [x] integration/integration.test
- [x] examples.test
- [x] functional.test
- [x] responder.test
- [x] responderResponse.test
- [x] adapters.amqp.publisher.test
- [x] config.test
- [x] request.test
- [x] channelManager.test
- [x] messageFactory.test
- [x] support.logger.test
- [x] serviceDetails.test
- [x] support.generateId.test
- [x] support.helpers.test
- [x] collector.test
- [x] requester.test

**Comment by galk-in** [comment]
# Clean up tasks

- [ ] typescript 2.1 ?
- [ ] .npmignore
- [ ] autopublish package
- [ ] set-up coverrals for typescript
- [ ] change naming for env variable
- [ ] add SSL for amqp adapter

# Types for all files
TBD

**Comment by plaenen** [comment]
Why going to TypeScript? 
Think we should stick to plain Javascript.

**Comment by galkin** [comment]
@plaenen hello.

MSB was written with ES5. For better maintainability we need to rewrite into ES6 or even ES7. We chose TypeScript, because it is last ES and types.

After this rewritting, the lib can be used in plain JS microservices.

**Comment by plaenen** [comment]
Just a few remarks: 
- MSB code should be stable, as it should not change often, therefore maintainability is in my opinion not the best argument for rewrite
- The only reason I could see and agree with is catching possible bugs on compile time. 
- Debugging might become more complex

**Comment by jupiter** [comment]
Nice work @galk-in 

It would be nice to catch up some time.

**Comment by jupiter** [comment]
@plaenen You may like https://medium.com/javascript-scene/the-shocking-secret-about-static-types-514d39bf30a3#.9zb60u9mk

I think TypeScript is okay if it leads to long-term developer happiness, but it should be clear what the value actually is. Since this is a library should be optimized for high throughput, and would generally be a hot spot, we should be careful not to introduce overhead with abstractions such as Promises.
