### ISSUE TITLE
AMQP messages inconsistency.

### ISSUE THREAD

**Issue by Kumjami** [tcdl/msb#125]
Using AMQP broker (RabbitMQ) in a simple use case: _publish/subscribe_; there is a **problem with the message format**. 

Given the following producer: 

``` js
'use strict';

const msb = require('msb');

const channelManager = msb.channelManager;
const messageFactory = msb.messageFactory;
const producer = channelManager.findOrCreateProducer('testing:topic', { type: 'fanout' });

const message = messageFactory.createBroadcastMessage({
    namespace: 'testing:topic'
});
message.payload = {
  message: 'test'
};

producer.publish(message, function (err) {
    if(err) return console.error(err);
    console.log('Message > ', message);
    process.exit(1);
});
```

And the following consumer: 

``` js
'use strict';

const msb = require('msb');

const consumer = msb.channelManager
.findOrCreateConsumer('testing:topic', { durable: true });

consumer.on('message', function (message) {
    console.log('Consumed > ', JSON.stringify(message));
}).on('error', function (err) {
    console.error('ERROR: ', err)
});
```
### Current behaviour:

The message is sent through RabbitMQ, consumer is receiving it, but rejecting it due to a error while validating received message.
Whoever is using `msb` doesn't get any information regarding what's happening with messages.  
### Expected behaviour:

User should be noticed when something happen (`message` or `error` event should be triggered). 
Using a straightforward example shouldn't give any error. It should just deliver the message and be emitted within the `message` event. 
#### Error analysis

After analysing the error I've found the cause of the error: 
As I said, it's due to a validation format error. Concretely the `message.meta.publishedAt` field.
After debugging I realised that we were getting a value of `null` on the consumer, while the validation expect it to be `string` [see](https://github.com/tcdl/msb/blob/master/schema.json#L27).
I was looking where it was introduced to see if I was missing something (options field, maybe). 
Using the [`messageFactory`](https://github.com/tcdl/msb/blob/master/lib/messageFactory.js) (_which, by the way, is not documented_) and the [`createBroadcastMessage`](https://github.com/tcdl/msb/blob/master/lib/messageFactory.js#L44-L51) function, we can see how [`createMeta`](https://github.com/tcdl/msb/blob/master/lib/messageFactory.js#L86-L96) is invoked and within it [`publishedAt` is set to null](https://github.com/tcdl/msb/blob/master/lib/messageFactory.js#L92)

So, [`createBroadcastMessage`](https://github.com/tcdl/msb/blob/master/lib/messageFactory.js#L44-L51) is generating a message which is not valid according to [`schema.json`](https://github.com/tcdl/msb/blob/master/schema.json).
#### Test

[AMQP integration tests](https://github.com/tcdl/msb/blob/master/test/integration/integration.test.js) are working also with a inconsistent message, which is built as a [fixture](https://github.com/tcdl/msb/blob/master/test/integration/fixtures/integration_consumer_basic.json).  
As you can see, this fixture doesn't have the `publishedAt` field. After adding it tests **fail** as follows: 
![pasted image at 2016_10_21 12_31 pm](https://cloud.githubusercontent.com/assets/8338963/19600108/caa33d22-97a3-11e6-8f3d-53e4838d1c56.png)
### Easy and quick fix (proposal)
- 1. Initialising the `publishedAt` and adding it to the fixtures for the integration tests.

``` js
 ...
return {
    ttl: (config && config.ttl) || null,
    createdAt: new Date(),
    publishedAt: new Date(),
    durationMs: null,
    serviceDetails: serviceDetails
  };
...
```
- 2. Add null as a valid value for `publishedAt`. But it may be not valid to _business_. 

``` js
     ...
       "publishedAt": { "type": ["string", "null"], "format": "date-time" },
     ...
```

In order to give users insights of what's happening, the [`onValidationError`](https://github.com/tcdl/msb/blob/master/lib/channelManager.js#L135-L137) should emit an error event.

**Comment by Kumjami** [comment]
Regarding the 1 proposal. Given that there is a [test](https://github.com/tcdl/msb/blob/master/test/messageFactory.test.js#L65-L76) which is ensuring that the date is `null`. I assume that there is a reason for it to be `null`. So the 2nd one should be the way to go. 

I'm submitting a PR soon with it.

**Comment by galkin** [comment]
Hello, @Kumjami. You wrote an awesome issue! Thank you!

As hot-fix I updated `schema.json` file. You can check it in v0.11.5. If all is okay for you, please close the issue.

**For your information:** As you can see at the example https://github.com/tcdl/msb/blob/master/example/pubsub/broadcaster.js#L22, now you should use `completeMeta` function.

I understand, the demand to use `completeMeta` before every publishing is strange. I hope, our team will improve the API in the future. It will be after we finish rewriting the lib into typescript for better maintainability.

**Comment by Kumjami** [comment]
@galk-in It's working now using 0.11.6 both, with or without calling `completeMeta`. 
Just checked that with 0.11.3 It worked also only by using `completeMeta`. 

Is there any reason for not calling `completeMeta` withing the `createBroadcastMessage` before returning the message?

**Comment by galkin** [comment]
You can have a big timeout from `createBroadcastMessage` to `publish`. Example:

``` javascript
...
const message = messageFactory.createBroadcastMessage({
    namespace: 'testing:topic'
});
message.payload = {
  message: 'test'
};

//request to database for 2-3second
message.payload.infoFromDB = resultFromDataBase

messageFactory.completeMeta(message, message.meta);
...//Only now you are publishing.
```

In refactoring phase we will improve this behavior. So publish function will completeMeta.

**Comment by Kumjami** [comment]
@galk-in Thanks, it makes a lot of sense :sweat_smile:

Closing.
