### ISSUE TITLE
Publish callback never triggered. 

### ISSUE THREAD

**Issue by Kumjami** [tcdl/msb#136]
Hi!

I've been trying to debug a problem I have while working with components that use MSB and are orchestrated with doker.  

---------
## Summary: 

The `publish` callback  is never triggered if when the MSB module is initialised there is no available connection. 

----------
#### Environment:

- Ubuntu 16.04
- RabbitMQ
- Node 6.9
- Docker 
- Docker-compose 

#### MSB
- 0.11.6

#### Other libraries
- express 4.14.0

## Problem description

If there is no available RabbitMQ connection while trying to initialise a producer: 
```js
const msb = require('msb');
const config = require('./config');

const producer = msb.channelManager
  .findOrCreateProducer(config.amqp.topic, { durable: true });
```
Then, while publishing a message: 
```js
  let msg = msb.messageFactory.createBroadcastMessage({
    namespace: config.amqp.topic
  });
  msg.payload = {m: 0};
  msb.messageFactory.completeMeta(msg, msg.meta);
  producer.publish(msg, (err) => {
    if(err) {
      console.error(err);
      process.exit(0);
    }
    console.log("message published succesfully");
  });
```
The `publish` callback will never be triggered and the message wont be published. 

## Expected behaviour

As a desirable behaviour I would like it to try to connect if it has no already a connection while publishing. Also, in the case that it's not possible (still without connectivity with RabbitMQ) the callback should be triggered reporting a connectivity problem.  

## Current behaviour

Nothing happens, callback is never triggered. 

## Context

I found the error because docker-compose can ensure that containers that are dependencies of others are running before launching them, but it can't ensure that the main container service is ready to address requests properly. 
So when I _deploy_ my docker containers, my process tries to connect before the rabbit service is ready. Later, when the main service needs the connection rabbit is ready but MSB doesn't try again to check if it is possible to communicate with Rabbit. 

### Full example code: 

```js
'use strict';

const express = require('express');
const app = express();

const msb = require('msb');
const config = require('./config');

const producer = msb.channelManager
  .findOrCreateProducer(config.amqp.topic, { durable: true });

app.get('/', (req, res) => {
  let msg = msb.messageFactory.createBroadcastMessage({
    namespace: config.amqp.topic
  });
  msg.payload = {m: 0};
  msb.messageFactory.completeMeta(msg, msg.meta);
  producer.publish(msg, (err) => {
    if(err) {
      console.error(err);
      process.exit(0);
    }
    console.log("message published succesfully");
    res.send('ok'); 
  });
});

app.listen(3000, () => console.log('Server listening at port: 3000'));

```

**Comment by Kumjami** [comment]
After trying to debug the error I found that it's something related with the adapter initialisation config (in this case AMQP).

As I'm using docker, I need to use _env vars_ in order to connect with the _remote_ RabbitMQ instance. 
There is a estrange behaviour there with the MSB:
In case you try to create the producer, the `channelManager` that is generated seems that doesn't use _env vars_, so it tries to connect to the localhost instance (which doesn't exist) so it never connects. And we have 2 problems there.
1. It doesn't use env vars
2. It doesn't report the connectivity problem.


On the other hand, if before creating a `producer` with `findOrCreateProducer` we create a `consumer` with `findOrCreateConsumer` both, consumer and producer, work.

**Comment by jupiter** [comment]
I don't know what you mean with "it doesn't use envs". 

I think [the driver](https://github.com/dropbox/amqp-coffee#new-amqp-coffeeconnectionoptionscallback) default behaviour is to keep retrying to connect, every [reconnectionTimeout](https://github.com/dropbox/amqp-coffee/blob/master/src/lib/defaults.coffee#L26). We could consider changing the behaviour to callback on a connection timeout. It does however mean that you have to turn off the automatic reconnection feature.

**Comment by Kumjami** [comment]
To reproduce the error: 

1. Download and install [federated-search initial branch](https://github.com/ThomasCookOnline/federated-search/tree/initial-commit)
2. Delete/comment [this 2 lines](https://github.com/ThomasCookOnline/federated-search/blob/initial-commit/adapters/rest-api/index.js#L10-L11)
3. Open browser/postman and make request at localhost:3005

**Comment by jupiter** [comment]
I am able to reproduce this. Firstly, it is not valid to specify `durable: true` on the publisher, as the publisher is not responsible for setting up queues. However, this would simply have no effect and is not the source of the problem.

The problem was introduced with https://github.com/tcdl/msb/pull/118/commits/b3cfa2e9991014df15e38b53e24671135b338075 and is due to the adapter config not yet being loaded at the time of creating the producerConfig here https://github.com/tcdl/msb/blob/master/lib/channelManager.js#L86.
