### ISSUE TITLE
Requester/collector 'error' event does not 'end' requester/collector

### ISSUE THREAD

**Issue by jupiter** [tcdl/msb#15]
In particular, using `validateWithSchema.onEvent()` for requester 'response' event handler will mean that, in case of an error, the 'end' event will never be called. This is okay if you implement your handlers correctly, but this is not particularly clear with the API/docs as it is. We should consider either:
- change the behaviour so that an error always triggers the 'end' event, perhaps also passing the error to the 'end' event, i.e. `requester.on('end', function(err) { //... })`.
- require an errorHandler for `validateWithSchema.onEvent` and do not throw the error to be picked up by EventEmitter and improve documentation to help ensure that implementers do not forget to do what they need to do to properly end when encountering an error.

**Comment by plaenen** [comment]
I would opt for the second bit, thus requiring an errorHandler for the validateWithSchema.onEvent.

**Comment by jupiter** [comment]
Note that an 'error' event does `cancel()` the Collector, which means that once any error has occurred the Collector will not emit any further events, even if additional responses are received. This is in line with a general principle of failing fast.

The scenario I'm considering is that implementers can opt to ignore invalid messages i.t.o. Collector lifetime, i.e. continue to listen for more messages. Currently they can do this providing an errorHandler to `validateWithSchema.onEvent`.

We want the default behaviour to be in line with the most common implementation. Perhaps the dead-letter feature #33 would be instructive to deciding on a default behaviour for error-handling in Collectors.

**Comment by jupiter** [comment]
Since we won't be making any chances to error-handlng in Collectors #33, we only need to complete documentation for validateWithSchema #44. It is also now guaranteed that an error in the response event will not trigger an end event #49.
