### ISSUE TITLE
Tags 

### ISSUE THREAD

**Issue by plaenen** [tcdl/msb#20]
It would be nice to have a tags feature.

Sample use cases:  
1. adding a debug tag (tags : ['debug']) by a requester would result that all following tags would inherit those tags. The debug tag could be used to add additional debug information on messages. 
2. feature flags for multi-variance testing (tags: ['feature:fooService.fooFeature']) could be used for feature testing on service level. An API could add those tags on the message. For example an optimizely test could result in some feature flags to be set for 20% of the traffic. The service should use a middleware to use the available tags on message level. 

@jupiter , what's your opinion?

**Comment by jupiter** [comment]
Tags should be specified on the config for requesters and on the base message. We can use the context for inheriting tags throughout.

We'll implement the feature on http2bus for translating a tags header/magic-query-param to a requester config.
