### ISSUE TITLE
[1.x] silent message rejection in case of validation error

### ISSUE THREAD

**Issue by sergiv83** [tcdl/msb#205]
I've faced with a bit confusing behavior in case of msb message schema validation error. Msb actually drops the message without any notification for library user (via log or somehow) or error propagation.
https://github.com/tcdl/msb/blob/876a2312e331ddf20e24325632a31c5e6899345c/lib/channelManager.js#L145

**Comment by OleksiiSliusarenko** [comment]
https://www.npmjs.com/package/msb released version 1.2.2 with fix
