### ISSUE TITLE
Should null be equivalent to missing value in message?

### ISSUE THREAD

**Issue by vso-tc** [tcdl/msb#35]
It would be convenient if having some message field missing would be equivalent to having that field equal to null.

This rule however is sometimes violated in the current implementation. For example ack responses do not have any payload but to make JSON-validation happy we need to specify `payload: null` in such case.

What do you think about this proposal?

**Comment by jupiter** [comment]
I agree that a null value is way too subtle to carry important meaning. In the case of the `payload` and `ack` sections on the envelope, we could treat it as equivalent by allowing the values to not be specified. 

~~In our message archive, we would lose the ability to search/filter for/out non-payload-containing messages, previously called acks, as there is no way in the query language to specify that a `payload` must not exist, although you can specify that a payload should be null. The questions then are, do we need to continue do searches like this, and is there harm in requiring the payload value to be either a null or object value?~~

To implement this change we should make a schema rule that 'null' should never be a valid value for a required field. Does this sound right?

**Comment by vso-tc** [comment]
Hm...

You've brought up a very important point about ability to search message archive for missing/null value. What archive to you mean? If you're talking about elasticsearch then it seems that there builtin filters to do it: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-missing-filter.html. 

Am I missing something?

**Comment by jupiter** [comment]
You're right, it is possible to query for non-existent values.

So you're in agreement that we should make a schema rule that 'null' should never be a valid value for a required field?

**Comment by vso-tc** [comment]
Yeah, I think that's a good idea.
