### ISSUE TITLE
SSL support in AMQP adapter

### ISSUE THREAD

**Issue by vso-tc** [tcdl/msb#36]
Currently AMQP adapter does not support SSL connection to RabbitMQ. Implementing it might be useful.

The simple SSL support was implemented in msb-java (https://github.com/tcdl/msb-java/pull/253). It currently doesn't have any certificate check and supports only TLSv1.

Do you think implementing such feature would be useful for msb?

**Comment by vso-tc** [comment]
The reason for this improvement is that we could host RabbitMQ on external server (for example AWS). In this case it would be good to have secure connection to it not to expose any sensitive data which might be present in payload)

**Comment by KimEeckhout** [comment]
In our specific case, we needed an SSL connection because some of our applications are hosted in an AWS environment, which means that the data we send from those applications goes over the internet. Therefore we need to make sure that that data is encrypted when it goes over the wire.

**Comment by jupiter** [comment]
Currently it is possible to use SSL with the AMQP adapter for MSB, but you would have to provide SSL options as per [driver options](https://github.com/dropbox/amqp-coffee#new-amqp-coffeeconnectionoptionscallback), to be loaded via [config file at `MSB_CONFIG_PATH`](https://github.com/tcdl/msb#configuration).

However, given that our EC2 services run in a VPC and that we do not treat our bus, and its consumers, as trusted anyway, I see no need for the general use of SSL in communication with our bus. Security and privacy are only as strong as the weakest link, and we have many weaker links, such as with HTTP reverse proxying, than our connection to the AMQP server. I would therefore advise against the general use of SSL with the bus unless it forms part of a clear and comprehensive plan.

**Comment by vso-tc** [comment]
Thank you for the clear explanation, @jupiter !
