### ISSUE TITLE
Provide a way for consumers to do explicit AMQP acknowledgements

### ISSUE THREAD

**Issue by vso-tc** [tcdl/msb#48]
We should provide ability to a microservice developer to send explicit AMQP acks for consumed messages to provide generic way to deal with common errors.

As an example let's consider a microservice that has to access a database to process an incoming request. Also let's assume that it's a very important microservice that must not skip messages. In case if the DB is not available and hence the request cannot be processed immediately the only option I see with the current msb implementation would be to store that request somewhere (but what's if _that_ store fails?) and "replay" it at some point in future when DB is accessible again.

It seems to be quite typical scenario that shouldn't require that much work from a microservice developer.

AMQP brokers have queues that can store messages and they provide a way to explicitly acknowledge a message which means that it's considered successfully processed and hence is removed from its queue.
Also they provide [negative acknowledgements](https://www.rabbitmq.com/nack.html) which allow either to remove the message from queue or requeue it.

So AMQP acks/nacks seem to be a good tool to solve the problem. The issue is that only microservice developer knows when a message can be considered as being "successfully processed" so we cannot do it behind the scenes on msb level. Instead we should provide a way for developers to perform acks/nacks when needed.

Open questions:
- design actual API for acks/nacks available for microservice developers
- AMQP adapter support acks/nacks natively, but what's about redis and local adapters? Can we implement this mechanism for them as well?

**Comment by jupiter** [comment]
Firstly, I think we should start by implementing this only for Pub/Sub interfaces, **not yet** for Collector, Requester or Responder.

I suggest something like this:

``` js
var channel = msb
.channelManager
.findOrCreateConsumer('test:pubsub', {
  requiresConfirmation: true
})
.on('message', function(message) {
   // ... processing
  channel.confirmProcessedMessage(message);
})
.on('error', debug)
```

We can also consider `channel.rejectMessage(message);`.

**Comment by jupiter** [comment]
Note: this mechanism is only for avoiding loss in case of serious error. Other mechanisms should be in place to ensure general durability.

**Comment by vso-tc** [comment]
I think implementation of `channel.confirmProcessedMessage(message)` might be tricky because to send the AMQP ack back you need to have so-called "delivery tag" which is not a part of message body. Also it will force developers to use low-level entities like `channel` while in most cases they only need to provide middleware function to `responderServer`.

Wouldn't it be more convenient to enrich the first argument of middleware function (`request`) with functions like `confirm`?

**Comment by jupiter** [comment]
I'm talking about the lower-level implementation. ResponderServer implementation would come later.

At this lower level, it would mean that channelManager must keep a reference/map of MSB message to adapter-level message and it should use that to confirm at the adapter level.

**Comment by vso-tc** [comment]
1. If we're talking about lower-level implementation then your proposal is reasonable. Do you propose to implement this change in master first and then investigate possible API change on `Requester`, `Responser` etc level?

2.

> Note: this mechanism is only for avoiding loss in case of serious error. Other mechanisms should be in place to ensure general durability.

To be on the same page I'd like to clarify what mechanism from your standpoint should be used in my example (broken database connection).

**Comment by jupiter** [comment]
For a responder service, a broken database connection should mean that your service responds with errors, so that failure can cascade to the source and feedback is clear to all systems. If you have a consumer-only service that is writing critical data to a database, and the database connection is broken, it would be serious, so you will want to error via your normal way, e.g. log and exit, and at the same time not lose any unprocessed messages, by not acking to the broker.

**Comment by vso-tc** [comment]
Totally agree with you
